### ISSUE TITLE
Support Supernova game mode

### ISSUE THREAD

**Issue by donbonifacio** [orionsbelt-battlegrounds/obb-rules#9]

**Comment by quimrstorres** [comment]
Since we're in the space wars theme, I feel compelled to call this something a bit different. Two types of things come to my mind:
* Something that suggests the killing of a commanding officer;
* Generic cosmology terms that suggest the destruction of the "star" of the fleet.

**Comment by quimrstorres** [comment]
@donbonifacio , I changed the game mode to Supernova like we spoke AFK.

**Comment by quimrstorres** [comment]
@donbonifacio I will also change the description to explain the new Supernova game mode. Should I also add it somewhere in the docs?
